//
//  UIColor+Dresstime.swift
//
//  Generated by Zeplin on 11/16/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

import UIKit

extension UIColor {
    class func drsWhiteColor() -> UIColor {
        return UIColor(white: 216.0 / 255.0, alpha: 1.0)
    }

    class func drsBlackColor() -> UIColor {
        return UIColor(white: 0.0, alpha: 1.0)
    }

    class func drsMacaroniAndCheese50Color() -> UIColor {
        return UIColor(red: 235.0 / 255.0, green: 175.0 / 255.0, blue: 73.0 / 255.0, alpha: 0.5)
    }

    class func dressTimeOrange() -> UIColor {
        return UIColor(red: 235.0 / 255.0, green: 175.0 / 255.0, blue: 73.0 / 255.0, alpha: 1.0)
    }
}
